- name: configuring backend server
  hosts: backend
  become: yes
  tasks:
   - name: disbling nodejs
     ansible.builtin.command: dnf module disable nodejs -y
   - name: enable node 20
     ansible.builtin.command: dnf module enable nodejs:20  -y
   - name: install nodejs
     ansible.builtin.package:
       name: nodejs
       state: installed
   - name: set expense user
     ansible.builtin.user:
        user: expense
   - name: makedirectory
     ansible.builtin.file:
        path: /app
        state: directory
   - name: download code
     ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
   - name: unzip code
     ansible.builtin.un_archive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes
   - name: install npm
     community.common.npm:
       path: /app
   - name: copy service file
     ansible.builtin.copy:
       src: backend.service
       dest: /etc/systemd/system/backend.service
   - name: import mysql database
     community.myslq.mysql_db:
        state: import
        login_user: root
        login_password: ExpenseApp@1
        login_host: 172.31.20.127
        target: /app/schema/backend.sql
   - name: restart or reload backend
     ansible.builtin.service:
      enabled: yes
      state: restarted
      daemon_reload: true
      name: backend 

    

