- name: configuring databaseserver
  hosts: db 
  become: yes
  tasks:
    - name: mysql libraries
      ansible.builtin.pip:
         name: "{{ item }}"
         executable: pip3.9
      loop:
        - cryptography
        - PyMySQL

    - name: install mysql server
      ansible.builtin.package:
         name: mysql-server
         state: installed
    - name: start and and enabling the server
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: configuring the userdetails
      community.mysql.mysql_info:
       login_user: root
       login_password: ExpenseApp@1
       login-host: 172.31.29.227
       register:  mysql_info
       #ignore-errors: yes
    - name: printing info
      ansible.builtin.debug:
        msg: " {{ mysql_info }}"
    - name: setup the db password 
      ansible.builtin.command: "mysql_secure_installation --set-root-pass ExpenseApp@1 "
      when: mysql_info failed is true