- name: configuring databaseserver
  hosts: db 
  become: yes
  tasks:
    - name: install mysql server
      ansible.builtin.package:
         name: mysql-server
         state: installed
    - name: start and and enabling the server
      ansible.buitin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: configuring the userdetails
      community.mysql.mysql-info:
       login_user: root
       login_password: ExpenseApp@1
       login-host: 172.31.29.227
       register: "{{ mysql-info }}"
       ignore-errors: yes
    - name: printing info
      ansible.builtin.debug:
        msg: " {{ mysql-info }}"
    - name: setup the db password 
      ansible.builtincommand: "mysql_secure_installation --set-root-pass ExpenseApp@1 "
      when: mysql-info failed is true