- name: alldatatypes
  hosts: web
  vars:
    course_name: " devops"
    duration: 120
    topic:
     - linux
     - shell-scripting
     - ansible
     - aws
  tools:
     ci: jenkins
     cloud: aws
     containerization: docker
  tasks:
    - name: all types of variables
      ansible.builtin.debug:
        msg: "this is all data types class for course : {{ course_name }} which has duration of {{ duration }} includes topics {{ topics }} using tools: {{ tools }} "