- name: alldatatypes
  hosts: web
  vars:                 # var is also a map/ dictnory datatype
    course_name: " devops" # sting 
    duration: 120        # number
    topic:    # topic is list data type list always start with "-"
     - linux
     - shell-scripting
     - ansible
     - aws
    tools:    # tools are maps/dictnory datatype
     ci: jenkins
     cloud: aws
     containerization: docker
  tasks:
    - name: all types of variables
      ansible.builtin.debug:
        msg: "this is all data types class for course : {{ course_name }} which has duration of {{ duration }} includes topics {{ topics }} using tools: {{ tools }} "